#!/usr/bin/env sh
[ -z $1 ] && echo 'No expression to replace' && exit 1 || IF=$1
[ -z $2 ] && OF= || OF=$2
[ -z $3 ] && SEP=@ || SEP=$3

EXPR="s${SEP}${IF}${SEP}${OF}${SEP}g"

echo "$1 -> $2\n$EXPR"

rg -l $IF | xargs -d '\n' sed -i $EXPR
