#!/usr/bin/env sh
# image resolution
readonly RESOLUTION=1920x1080
# tags comma-separated
readonly TAGS=$WALLPAPER_TAGS
readonly URL="https://source.unsplash.com/${RESOLUTION}/?${TAGS}"
# echo "Fetching image from $URL"

set_bg() {
  feh --bg-fill $URL || feh --bg-fill --randomize ~/pictures/wallpapers
}

# set bg one time
[ "$1" = once ] && set_bg && exit 0

# set bg every 10 minutes
while true; do
  set_bg
  sleep 10m
done
