#!/usr/bin/env sh
# image resolution
# readonly RESOLUTION=
# tags comma-separated
# readonly TAGS=
# readonly URL="https://source.unsplash.com/${RESOLUTION}/?${TAGS}"
readonly URL="https://source.unsplash.com/collection/1343739"
# echo "Fetching image from $URL"

set_bg() {
  feh --bg-fill $URL || feh --bg-fill --randomize ~/pictures/wallpapers
}

# set bg one time
[ "$1" = once ] && set_bg && exit 0

# set bg every 10 minutes
while true; do
  set_bg
  sleep 10m
done
